name: Deploy to Firebase App Distribution from Push to Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Load OpenCV
        uses: Dovyski/setup-opencv-action@v1
        with:
          opencv-version: '4.5.2'

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build debug
        run: ./gradlew assembleDebug

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: treeo-mobile-app-testers
          file: app/build/outputs/apk/app.apk


